spring.application.name=MemoriaVivaTech
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_SoulStory
spring.datasource.username=postgres
spring.datasource.password=Upc2026
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-stacktrace=never

logging.level.root=INFO
logging.level.com.upc.ss=DEBUG

jwt.secret=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==
ip.frontend=http://localhost:4200
spring.security.user.password=unused

stability.api.key=sk-9KVApexjWh0G7ySfXJm9yzlUkapcrTpoakp0bzIa5QYCnVCQ
stability.api.url=https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image
spring.codec.max-in-memory-size=20MB

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=ddmsftiky
cloudinary.api-key=634632549765881
cloudinary.api-secret=BeX-MBbEYunRff33rtvP0WnzrHc